import { jsPDF } from 'jspdf';
import { QRCodeCanvas } from 'qrcode.react';
import { useRef, useEffect, useState } from 'react';
import { Button } from '@/components/ui/button';
import { Download, CheckCircle, Smartphone, Loader2 } from 'lucide-react';
import { toast } from 'sonner';

interface ReceiptProps {
  petition: {
    id: string;
    title: string;
    category: string;
    created_at: string;
    citizen_name: string;
  };
  t: any;
}

// Returns the correct base URL for QR codes.
// When running locally (localhost), uses the machine's network IP from .env
// so that mobile phones on the same WiFi can scan and open the track page.
function getTrackingBaseUrl(): string {
  const origin = window.location.origin;
  const localIp = import.meta.env.VITE_LOCAL_IP;
  const isLocalhost = origin.includes('localhost') || origin.includes('127.0.0.1');
  
  if (isLocalhost && localIp) {
    const port = window.location.port || '8080';
    return `http://${localIp}:${port}`;
  }
  return origin;
}

export function PetitionReceipt({ petition, t }: ReceiptProps) {
  const qrRef = useRef<HTMLDivElement>(null);
  const [qrLoaded, setQrLoaded] = useState(false);
  const [isDownloading, setIsDownloading] = useState(false);
  
  // Helper to remove non-Latin characters from PDF text to avoid jsPDF crashes
  const sanitizeText = (text: string) => {
    if (!text) return '';
    // Characters outside WinAnsi range can crash jsPDF standard fonts
    // For now, replacing Tamil with '?' to ensure the rest of the PDF is generated
    return text.toString().normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[^\x00-\x7F]/g, "?");
  };

  useEffect(() => {
    if (qrRef.current) setQrLoaded(true);
  }, []);

  const generatePDF = async () => {
    setIsDownloading(true);
    try {
      const doc = new jsPDF();
      const trackingUrl = `${getTrackingBaseUrl()}/track/${petition.id}`;

      // Header
      doc.setFillColor(37, 99, 235); // Primary Blue
      doc.rect(0, 0, 210, 40, 'F');
      
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(22);
      doc.setFont('helvetica', 'bold');
      doc.text('Smarter Petitions', 105, 20, { align: 'center' });
      doc.setFontSize(10);
      doc.text('Official Digital Petition Receipt', 105, 30, { align: 'center' });

      // Content
      doc.setTextColor(33, 33, 33);
      doc.setFontSize(14);
      doc.text('PETITION DETAILS', 20, 55);
      doc.setLineWidth(0.5);
      doc.line(20, 58, 190, 58);

      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      
      // Sanitize fields to prevent PDF library crash on Tamil/Unicode characters
      const titleLines = doc.splitTextToSize(sanitizeText(petition.title), 120);
      const details = [
        ['Petition ID:', petition.id || 'N/A'],
        ['Submitted By:', sanitizeText(petition.citizen_name || 'Anonymous')],
        ['Category:', sanitizeText(t(`dept_${petition.category}`) || petition.category)],
        ['Date:', new Date(petition.created_at).toLocaleString()],
        ['Status:', 'Awaiting Admin Review']
      ];

      let y = 70;
      doc.setFont('helvetica', 'bold');
      doc.text('Title:', 20, y);
      doc.setFont('helvetica', 'normal');
      doc.text(titleLines, 60, y);
      y += (titleLines.length * 5) + 5;

      details.forEach(([label, value]) => {
        doc.setFont('helvetica', 'bold');
        doc.text(label, 20, y);
        doc.setFont('helvetica', 'normal');
        doc.text(String(value), 60, y);
        y += 10;
      });

      // Verification Section
      doc.setFillColor(248, 250, 252);
      doc.rect(20, y + 10, 170, 60, 'F');
      
      doc.setFontSize(12);
      doc.setFont('helvetica', 'bold');
      doc.text('VERIFICATION QR CODE', 105, y + 25, { align: 'center' });
      
      doc.setFontSize(9);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(100, 100, 100);
      doc.text('Scan this code with your phone camera to track live status.', 105, y + 34, { align: 'center' });

      // Add QR Code with nested try-catch to prevent a single failure from blocking the entire download
      try {
        const canvas = qrRef.current?.querySelector('canvas');
        if (canvas) {
          // Use high quality PNG for better scanning
          const qrImage = canvas.toDataURL('image/png', 1.0);
          if (qrImage && qrImage.length > 50) {
            doc.addImage(qrImage, 'PNG', 85, y + 42, 40, 40, undefined, 'FAST');
            
            // Add a clean border around the QR area
            doc.setDrawColor(220, 220, 220);
            doc.setLineWidth(0.1);
            doc.rect(84, y + 41, 42, 42);
          }
        }
      } catch (qrErr) {
        console.error("QR Image skip:", qrErr);
      }

      // Footer
      doc.setFontSize(8);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(150, 150, 150);
      doc.text('Generated by Smarter Petitions AI System. This is a computer-generated document.', 105, 285, { align: 'center' });

      const filename = petition.id ? `Receipt_${String(petition.id).slice(0, 8)}.pdf` : 'Receipt.pdf';
      doc.save(filename);
      toast.success("Receipt downloaded successfully!");
    } catch (err: any) {
      console.error("PDF Download Error:", err);
      // Give the user a more specific error message to help debug
      toast.error(`Download failed: ${err.message || 'Check your browser settings'}`);
    } finally {
      setIsDownloading(false);
    }
  };

  return (
    <div className="w-full flex flex-col items-center gap-4">
      {/* Hidden QR for PDF Generation */}
      {/* Render QR code off-screen for PDF generation reliability (using opacity instead of display:none) */}
      <div ref={qrRef} className="absolute -left-[9999px] top-0 opacity-0 pointer-events-none" aria-hidden="true">
        <QRCodeCanvas 
          value={`${getTrackingBaseUrl()}/track/${petition.id}`} 
          size={512} // Increased resolution for better capture
          level="H"
          marginSize={2}
        />
      </div>

      <div className="bg-primary/5 border border-primary/20 p-6 rounded-2xl w-full flex flex-col items-center text-center gap-3">
        <div className="w-12 h-12 bg-primary/10 rounded-full flex items-center justify-center text-primary">
          <Smartphone className="w-6 h-6" />
        </div>
        <div className="space-y-1">
          <h4 className="font-bold">Track via QR Code</h4>
          <p className="text-xs text-muted-foreground">Scan the QR in your receipt to see live updates on your phone.</p>
        </div>
        
        <Button 
          onClick={generatePDF} 
          className="w-full gap-2 bg-slate-900 hover:bg-slate-800 text-white"
          disabled={!qrLoaded || isDownloading}
        >
          {isDownloading ? (
            <Loader2 className="w-4 h-4 animate-spin" />
          ) : (
            <Download className="w-4 h-4" />
          )}
          {isDownloading ? 'Preparing PDF...' : 'Download PDF Receipt'}
        </Button>
      </div>
    </div>
  );
}
